WINE_COUNTRIES = [
    ("FR", "France"),
    ("IT", "Italy"),
    ("ES", "Spain"),
    ("PT", "Portugal"),
    ("DE", "Germany"),
    ("AT", "Austria"),
    ("CH", "Switzerland"),
    ("GR", "Greece"),
    ("HU", "Hungary"),
    ("RO", "Romania"),
    ("BG", "Bulgaria"),
    ("HR", "Croatia"),
    ("SI", "Slovenia"),
    ("SK", "Slovakia"),
    ("CZ", "Czechia"),
    ("LU", "Luxembourg"),
    ("RS", "Serbia"),
    ("MK", "North Macedonia"),
    ("ME", "Montenegro"),
    ("BA", "Bosnia and Herzegovina"),
    ("AL", "Albania"),
    ("MD", "Moldova"),
    ("UA", "Ukraine"),
    ("GE", "Georgia"),
    ("AM", "Armenia"),
    ("TR", "Turkey"),
    ("CY", "Cyprus"),
    ("LB", "Lebanon"),
    ("IL", "Israel"),
    ("MA", "Morocco"),
    ("TN", "Tunisia"),
    ("ZA", "South Africa"),
    ("US", "United States"),
    ("CA", "Canada"),
    ("MX", "Mexico"),
    ("AR", "Argentina"),
    ("CL", "Chile"),
    ("UY", "Uruguay"),
    ("BR", "Brazil"),
    ("AU", "Australia"),
    ("NZ", "New Zealand"),
    ("JP", "Japan"),
    ("CN", "China"),
    ("GB", "United Kingdom"),
]
